### ISSUE TITLE
Error: Cannot find module 'identify.js'

### ISSUE THREAD

**Issue by jondot** [sdepold/node-imageable#7]
FYI: 
I'm getting this error, and I also saw that on the repository, the identify.js file is missing.

**Comment by sdepold** [comment]
i should really get email notifications work... arg!

Are you getting this error all the time or just every once and while?

**Comment by jondot** [comment]
all the time. it looked like npm dependency issues.
IIRC i explicitly installed identify and then everything worked.

**Comment by sdepold** [comment]
hmm pretty strange... the package.json should be correct o0

**Comment by sdepold** [comment]
I've just checked out the node-imageable-server app and got the same issue, due to upgrade conflicts with node 0.6. I update the package.json locally to the latest versions of express and connect. Due to the continuous upgrade process I ended up in the following situation:

```
>> npm list

npm WARN hashish 0.0.4 Unmet dependency in /Users/sdepold/Projects/node-imageable-server/node_modules/airbrake
npm WARN request 1.9.8 Unmet dependency in /Users/sdepold/Projects/node-imageable-server/node_modules/airbrake
npm WARN stack-trace 0.0.5 Unmet dependency in /Users/sdepold/Projects/node-imageable-server/node_modules/airbrake
npm WARN xmlbuilder 0.1.5 Unmet dependency in /Users/sdepold/Projects/node-imageable-server/node_modules/airbrake
npm WARN identify.js >=0.1.2 Unmet dependency in /Users/sdepold/Projects/node-imageable-server/node_modules/imageable
npm WARN eyes >=0.1.6 Unmet dependency in /Users/sdepold/Projects/node-imageable-server/node_modules/vows
imageable@0.1.0 /Users/sdepold/Projects/node-imageable-server
├─┬ airbrake@0.2.3 
│ ├── UNMET DEPENDENCY hashish 0.0.4
│ ├── UNMET DEPENDENCY request 1.9.8
│ ├── UNMET DEPENDENCY stack-trace 0.0.5
│ └── UNMET DEPENDENCY xmlbuilder 0.1.5
├─┬ connect@1.8.2 
│ ├── formidable@1.0.8 
│ ├── mime@1.2.4 
│ └── qs@0.4.0 
├─┬ express@2.5.2 
│ ├── mime@1.2.4 
│ ├── mkdirp@0.0.7 
│ └── qs@0.4.0 
├─┬ imageable@0.8.6 
│ └── UNMET DEPENDENCY identify.js >=0.1.2
└─┬ vows@0.6.0 
  └── UNMET DEPENDENCY eyes >=0.1.6
```

After doing `node app.js` I got the same error as you reported "Cannot find module 'identify.js'". I fixed it with `rm -rf node_modules` and a `npm install`. Is this working for you as well?
